In [7]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
import sys
sys.path.append('..')
import numpy as np
import tensorflow as tf
from dset_helpers import data_given_param

In [9]:
from train_VMC import Train_w_VMC
from train_data import Train_w_Data

In [10]:
Lx = 16
Ly = 16
Omega = 4.24
Rb = 1.15
V0 = Rb**6 * Omega
sweep_rate = 15
low = -1.545
midlow = 4.455
midhigh = 4.955
high = 13.455

# Training with VMC

In [5]:
def main():
    config = {
        'name': 'train_w_VMC updates', # A very random name for each experiment
        'Lx': 4,  # number of sites in x-direction                    
        'Ly': 4,  # number of sites in the y-direction
        'V': 7.,
        'Omega': 1.,
        'delta': 1.,
        'sweep_rate':15,
        
        'nh': 32,  # number of memory/hidden units
        'lr': 1e-3,  # learning rate
        'weight_sharing': True,
        'trunc': 100,
        'seed': 1234,
        
        'RNN': 'OneD',
        'MDGRU': True,
        'VMC_epochs':500,
        'Data_epochs':0,
        
        'ns': 1000,
        'batch_size': 100,
        
        'Print':True,
        'Write_Data': True,
        'CKPT':False,
        'Plot': True
        }
    
    return Train_w_VMC(config)


if __name__ == "__main__":
    model,e,v,c = main()

2022-11-21 17:10:40.745572: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Training a one-D RNN wave function with 32 hidden units and shared weights.
gru/gru_cell/kernel:0 (192,)
gru/gru_cell/recurrent_kernel:0 (3072,)
gru/gru_cell/bias:0 (192,)
dense/kernel:0 (64,)
dense/bias:0 (2,)
The sum of params is 3522
The experimental parameters are: V = 7.0, delta = 1.0, Omega = 1.0.
The system is an array of 4 by 4 Rydberg Atoms.
getting energy function!
CKPT OFF. Initializing from scratch.
Tracing!
Tracing!
Step #1
Energy = 1.26566743850708
Variance = 25.565046310424805
 
Step #2
Energy = 1.2188005447387695
Variance = 24.996910095214844
 
Step #3
Energy = 1.0860652923583984
Variance = 22.251754760742188
 
Step #4
Energy = 1.0323176383972168
Variance = 24.22313690185547
 
Step #5
Energy = 0.9132895469665527
Variance = 21.44253158569336
 
Step #6
Energy = 0.8179734945297241
Variance = 20.825191497802734
 
Step #7
Energy = 0.7435342073440552
Variance = 19.019975662231445
 
Step #8
Energy = 0.6571466326713562
Variance = 16.2246150970459
 
Step #9
Energy = 0.6967472434

Step #110
Energy = -0.28143900632858276
Variance = 0.7466211915016174
 
Step #111
Energy = -0.2911965548992157
Variance = 0.7467752695083618
 
Step #112
Energy = -0.2845303416252136
Variance = 0.7777100801467896
 
Step #113
Energy = -0.2792986333370209
Variance = 0.8932923078536987
 
Step #114
Energy = -0.2761714458465576
Variance = 0.8188190460205078
 
Step #115
Energy = -0.28040245175361633
Variance = 0.7369625568389893
 
Step #116
Energy = -0.2768494784832001
Variance = 0.8055142760276794
 
Step #117
Energy = -0.2815715968608856
Variance = 0.6913913488388062
 
Step #118
Energy = -0.28391608595848083
Variance = 0.8176640868186951
 
Step #119
Energy = -0.2659057080745697
Variance = 0.8487789630889893
 
Step #120
Energy = -0.27461734414100647
Variance = 0.7468721866607666
 
Step #121
Energy = -0.27717047929763794
Variance = 0.8024876713752747
 
Step #122
Energy = -0.29117539525032043
Variance = 0.6740491986274719
 
Step #123
Energy = -0.27998995780944824
Variance = 0.8448545932769775
 

Step #223
Energy = -0.3146026134490967
Variance = 0.4541982412338257
 
Step #224
Energy = -0.31383660435676575
Variance = 0.4472881257534027
 
Step #225
Energy = -0.32661956548690796
Variance = 0.41375067830085754
 
Step #226
Energy = -0.3279988467693329
Variance = 0.4223494529724121
 
Step #227
Energy = -0.3232048451900482
Variance = 0.4054405093193054
 
Step #228
Energy = -0.323115736246109
Variance = 0.45829132199287415
 
Step #229
Energy = -0.31945499777793884
Variance = 0.4473561644554138
 
Step #230
Energy = -0.3184129595756531
Variance = 0.43509382009506226
 
Step #231
Energy = -0.3244102895259857
Variance = 0.4017638564109802
 
Step #232
Energy = -0.31748276948928833
Variance = 0.5483891367912292
 
Step #233
Energy = -0.3224394917488098
Variance = 0.46968579292297363
 
Step #234
Energy = -0.32183611392974854
Variance = 0.4337860345840454
 
Step #235
Energy = -0.3243292272090912
Variance = 0.440107524394989
 
Step #236
Energy = -0.3228610157966614
Variance = 0.4590398967266083
 

Step #335
Energy = -0.33699309825897217
Variance = 0.4116760194301605
 
Step #336
Energy = -0.3424418866634369
Variance = 0.34700465202331543
 
Step #337
Energy = -0.3491229712963104
Variance = 0.3399392068386078
 
Step #338
Energy = -0.34054890275001526
Variance = 0.390778124332428
 
Step #339
Energy = -0.334929883480072
Variance = 0.3681577146053314
 
Step #340
Energy = -0.3275558352470398
Variance = 0.41691815853118896
 
Step #341
Energy = -0.34074902534484863
Variance = 0.3430178761482239
 
Step #342
Energy = -0.3501001000404358
Variance = 0.35686251521110535
 
Step #343
Energy = -0.3493019640445709
Variance = 0.35562101006507874
 
Step #344
Energy = -0.34075435996055603
Variance = 0.33956629037857056
 
Step #345
Energy = -0.33425435423851013
Variance = 0.3653624951839447
 
Step #346
Energy = -0.3331040143966675
Variance = 0.3780710697174072
 
Step #347
Energy = -0.3439425826072693
Variance = 0.35820823907852173
 
Step #348
Energy = -0.34377047419548035
Variance = 0.351602643728256

Step #447
Energy = -0.3772232234477997
Variance = 0.2026110291481018
 
Step #448
Energy = -0.3786412477493286
Variance = 0.20951177179813385
 
Step #449
Energy = -0.3696761727333069
Variance = 0.22267168760299683
 
Step #450
Energy = -0.3784137964248657
Variance = 0.20788875222206116
 
Saved training quantitites for step 450 in ./data/N_16/delta_1.0/OneD_rnn/train_w_VMC updates.
Step #451
Energy = -0.37918469309806824
Variance = 0.2109784036874771
 
Step #452
Energy = -0.37876254320144653
Variance = 0.2118072807788849
 
Step #453
Energy = -0.37970998883247375
Variance = 0.20459112524986267
 
Step #454
Energy = -0.38125574588775635
Variance = 0.20967644453048706
 
Step #455
Energy = -0.3805665671825409
Variance = 0.21748843789100647
 
Step #456
Energy = -0.38303500413894653
Variance = 0.17761893570423126
 
Step #457
Energy = -0.3795345723628998
Variance = 0.19406293332576752
 
Step #458
Energy = -0.3857041299343109
Variance = 0.1980387270450592
 
Step #459
Energy = -0.38335010409355164


In [6]:
def main():
    config = {
        'name': 'train_w_VMC updates', # A very random name for each experiment
        'Lx': 4,  # number of sites in x-direction                    
        'Ly': 4,  # number of sites in the y-direction
        'V': 7.,
        'Omega': 1.,
        'delta': 1.,
        'sweep_rate':15,
        
        'nh': 32,  # number of memory/hidden units
        'lr': 1e-3,  # learning rate
        'weight_sharing': True,
        'trunc': 100,
        'seed': 1234,
        
        'RNN': 'TwoD',
        'MDGRU': True,
        'VMC_epochs':500,
        'Data_epochs':0,
        
        'ns': 1000,
        'batch_size': 100,
        
        'Print':True,
        'Write_Data': True,
        'CKPT':False,
        'Plot': True
        }
    
    return Train_w_VMC(config)


if __name__ == "__main__":
    model,e,v,c = main()

Training a two-D RNN wave function with 32 hidden units and shared weights = True.
W_RNN:0 (8192,)
b_RNN:0 (32,)
Wg_RNN:0 (8192,)
bg_RNN:0 (32,)
Wmerge_RNN:0 (2048,)
Dense/kernel:0 (64,)
Dense/bias:0 (2,)
The sum of params is 18562
The experimental parameters are: V = 7.0, delta = 1.0, Omega = 1.0.
The system is an array of 4 by 4 Rydberg Atoms.
getting energy function!
CKPT OFF. Initializing from scratch.
Tracing!


/Users/mschuylerm/miniconda3/envs/2DRNN/lib/python3.9/site-packages/keras/legacy_tf_layers/base.py:573: UserWarning: `layer.updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  _add_elements_to_collection(self.updates, tf.compat.v1.GraphKeys.UPDATE_OPS)


Tracing!
Step #1
Energy = 1.956197738647461
Variance = 36.97549819946289
 
Step #2
Energy = 1.7666901350021362
Variance = 31.42721939086914
 
Step #3
Energy = 1.5559591054916382
Variance = 29.441957473754883
 
Step #4
Energy = 1.3247004747390747
Variance = 24.197940826416016
 
Step #5
Energy = 1.228780746459961
Variance = 24.248605728149414
 
Step #6
Energy = 1.0046764612197876
Variance = 21.161348342895508
 
Step #7
Energy = 0.9294073581695557
Variance = 18.55022430419922
 
Step #8
Energy = 0.7625314593315125
Variance = 17.181711196899414
 
Step #9
Energy = 0.671023428440094
Variance = 14.582074165344238
 
Step #10
Energy = 0.5474740266799927
Variance = 13.14123249053955
 
Step #11
Energy = 0.46244487166404724
Variance = 12.658523559570312
 
Step #12
Energy = 0.3659592866897583
Variance = 10.631499290466309
 
Step #13
Energy = 0.19554898142814636
Variance = 8.760804176330566
 
Step #14
Energy = 0.1323099434375763
Variance = 7.311886310577393
 
Step #15
Energy = -0.008568849414587021
V

Step #116
Energy = -0.3818500339984894
Variance = 0.4094421863555908
 
Step #117
Energy = -0.3882828950881958
Variance = 0.432768851518631
 
Step #118
Energy = -0.39289307594299316
Variance = 0.39788538217544556
 
Step #119
Energy = -0.388862669467926
Variance = 0.4872743487358093
 
Step #120
Energy = -0.3925250172615051
Variance = 0.44532984495162964
 
Step #121
Energy = -0.38170960545539856
Variance = 0.4912853538990021
 
Step #122
Energy = -0.39742034673690796
Variance = 1.0406780242919922
 
Step #123
Energy = -0.396763414144516
Variance = 0.5613093376159668
 
Step #124
Energy = -0.3821079134941101
Variance = 0.43025511503219604
 
Step #125
Energy = -0.3908367455005646
Variance = 0.5268309116363525
 
Step #126
Energy = -0.3953879475593567
Variance = 0.5332844257354736
 
Step #127
Energy = -0.3881596624851227
Variance = 0.44825565814971924
 
Step #128
Energy = -0.3856271505355835
Variance = 0.3913377821445465
 
Step #129
Energy = -0.3894450068473816
Variance = 0.4207645356655121
 
St

Step #228
Energy = -0.4231143295764923
Variance = 0.16225270926952362
 
Step #229
Energy = -0.42593634128570557
Variance = 0.16648142039775848
 
Step #230
Energy = -0.427336722612381
Variance = 0.16463232040405273
 
Step #231
Energy = -0.42462292313575745
Variance = 0.1504320353269577
 
Step #232
Energy = -0.4254588186740875
Variance = 0.1806771606206894
 
Step #233
Energy = -0.41945621371269226
Variance = 0.1422685831785202
 
Step #234
Energy = -0.4195607900619507
Variance = 0.17224866151809692
 
Step #235
Energy = -0.4220995306968689
Variance = 0.18919043242931366
 
Step #236
Energy = -0.4174998104572296
Variance = 0.17399480938911438
 
Step #237
Energy = -0.4179638624191284
Variance = 0.16008619964122772
 
Step #238
Energy = -0.4180206060409546
Variance = 0.16913238167762756
 
Step #239
Energy = -0.4221225678920746
Variance = 0.16490089893341064
 
Step #240
Energy = -0.42581188678741455
Variance = 0.13978025317192078
 
Step #241
Energy = -0.4194609522819519
Variance = 0.118330784142

Step #339
Energy = -0.44008690118789673
Variance = 0.06350503861904144
 
Step #340
Energy = -0.4434807598590851
Variance = 0.05048404633998871
 
Step #341
Energy = -0.44457757472991943
Variance = 0.07496979087591171
 
Step #342
Energy = -0.44202324748039246
Variance = 0.05772588402032852
 
Step #343
Energy = -0.44179174304008484
Variance = 0.06129923090338707
 
Step #344
Energy = -0.4374043941497803
Variance = 0.07666294276714325
 
Step #345
Energy = -0.43918755650520325
Variance = 0.05519342049956322
 
Step #346
Energy = -0.43892061710357666
Variance = 0.06445182859897614
 
Step #347
Energy = -0.44091543555259705
Variance = 0.07024898380041122
 
Step #348
Energy = -0.4377898573875427
Variance = 0.05941994488239288
 
Step #349
Energy = -0.44258567690849304
Variance = 0.06708125025033951
 
Step #350
Energy = -0.44045981764793396
Variance = 0.06100554019212723
 
Saved training quantitites for step 350 in ./data/N_16/delta_1.0/TwoD_rnn/train_w_VMC updates.
Step #351
Energy = -0.4389527440

Step #450
Energy = -0.44933778047561646
Variance = 0.03652951866388321
 
Saved training quantitites for step 450 in ./data/N_16/delta_1.0/TwoD_rnn/train_w_VMC updates.
Step #451
Energy = -0.44408321380615234
Variance = 0.044083353132009506
 
Step #452
Energy = -0.4485495090484619
Variance = 0.0474771186709404
 
Step #453
Energy = -0.4463901221752167
Variance = 0.03414454683661461
 
Step #454
Energy = -0.44522789120674133
Variance = 0.04123098403215408
 
Step #455
Energy = -0.4467114508152008
Variance = 0.032308753579854965
 
Step #456
Energy = -0.4469396471977234
Variance = 0.029435602948069572
 
Step #457
Energy = -0.44410550594329834
Variance = 0.04192475602030754
 
Step #458
Energy = -0.44421032071113586
Variance = 0.03109089843928814
 
Step #459
Energy = -0.4481259286403656
Variance = 0.03326214477419853
 
Step #460
Energy = -0.4480151832103729
Variance = 0.04107246920466423
 
Step #461
Energy = -0.44819653034210205
Variance = 0.033465005457401276
 
Step #462
Energy = -0.4462446272

In [15]:
from energy_func import buildlattice,construct_mats,get_Rydberg_Energy_Vectorized

In [16]:
interactions = buildlattice(4,4,trunc=1000)

In [17]:
energy_func_model = model.localenergy
energy_func_ext = get_Rydberg_Energy_Vectorized(interactions,model.logpsi)

getting energy function!


In [18]:
o,v_mat,cs = construct_mats(interactions,16)

In [19]:
test_sample1 = tf.ones((1,16),dtype=tf.int64)
test_sample2 = tf.zeros((1,16),dtype=tf.int64)
test_sample3 = tf.convert_to_tensor(np.random.randint(2,size=(1,16)),dtype=tf.int64)
logs_1 = model.logpsi(test_sample1)
logs_2 = model.logpsi(test_sample2)
logs_3 = model.logpsi(test_sample3)

In [22]:
energies_ext = energy_func_ext(1,1,7,o,v_mat,cs,test_sample3,logs_3)

shape of term 1:  (1,)
tf.Tensor(
[[1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [2.]
 [2.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [2.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [0.]
 [1.]
 [2.]
 [2.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [2.]
 [0.]
 [1.]
 [2.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [2.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [2.]
 [0.]
 [0.]
 [2.]
 [1.]
 [1.]
 [1.]
 [0.]
 [2.]
 [1.]
 [0.]
 [2.]
 [0.]
 [1.]
 [2.]
 [0.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [2.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [2.]
 [0.]
 [1.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [2.]
 [1.]
 [1.]
 [0.]], shape=(120, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

In [23]:
energies_model = model.localenergy(test_sample3,logs_3)

local energy in model function!
tf.Tensor([-7.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([7.], shape=(1,), dtype=float32)
tf.Tensor([7.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([7.], shape=(1,), dtype=float32)
tf.Tensor([7.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape

In [24]:
print(energies_ext)
print(energies_model)

tf.Tensor([16.89607], shape=(1,), dtype=float32)
tf.Tensor([16.896069], shape=(1,), dtype=float32)


# Train with Data

In [12]:
def main():
    config = {
        'name': 'train_w_VMC updates', # A very random name for each experiment
        'Lx': Lx,  # number of sites in x-direction                    
        'Ly': Ly,  # number of sites in the y-direction
        'V': V0,
        'Omega': Omega,
        'delta': low,
        'sweep_rate':15,
        
        'nh': 32,  # number of memory/hidden units
        'lr': 1e-3,  # learning rate
        'weight_sharing': True,
        'trunc': 100,
        'seed': 1234,
        
        'RNN': 'OneD',
        'MDGRU': True,
        'VMC_epochs':0,
        'Data_epochs':100,
        
        'ns': 1000,
        'batch_size': 100,
        
        'Print':True,
        'Write_Data': True,
        'CKPT':False,
        'Plot': True
        }
    
    return Train_w_Data(config)


if __name__ == "__main__":
    model,e,v,c = main()

Training a one-D RNN wave function with 32 hidden units and shared weights.
gru_1/gru_cell_1/kernel:0 (192,)
gru_1/gru_cell_1/recurrent_kernel:0 (3072,)
gru_1/gru_cell_1/bias:0 (192,)
dense_1/kernel:0 (64,)
dense_1/bias:0 (2,)
The sum of params is 3522
The experimental parameters are: V = 9.807377646249996, delta = -1.545, Omega = 4.24.
The system is an array of 16 by 16 Rydberg Atoms
getting energy function!
CKPT OFF. Initializing from scratch.
Tracing!
Tracing!
Step #1
Energy = 0.8438186049461365
Variance = 64.23004150390625
 
Step #2
Energy = -0.3126668632030487
Variance = 21.34415626525879
 
Step #3
Energy = -0.79667729139328
Variance = 5.418483734130859
 
Step #4
Energy = -0.8672019243240356
Variance = 2.889397382736206
 
Step #5
Energy = -0.8357366919517517
Variance = 4.009318828582764
 
Step #6
Energy = -0.8023437857627869
Variance = 5.10606050491333
 
Step #7
Energy = -0.8011882305145264
Variance = 5.245943546295166
 
Step #8
Energy = -0.8267074823379517
Variance = 4.2179207801

KeyboardInterrupt: 

# Vectorize energy....

In [95]:
from energy_func import buildlattice,construct_mats,get_Rydberg_Energy_Vectorized

In [96]:
interaction_list = buildlattice(3,3,trunc = 100)

In [97]:
print(np.array(interaction_list))

[[  1.   0.   1.]
 [  1.   1.   2.]
 [  1.   3.   4.]
 [  1.   4.   5.]
 [  1.   6.   7.]
 [  1.   7.   8.]
 [  1.   0.   3.]
 [  1.   3.   6.]
 [  1.   1.   4.]
 [  1.   4.   7.]
 [  1.   2.   5.]
 [  1.   5.   8.]
 [  8.   0.   4.]
 [  8.   3.   1.]
 [  8.   1.   5.]
 [  8.   4.   2.]
 [  8.   3.   7.]
 [  8.   6.   4.]
 [  8.   4.   8.]
 [  8.   7.   5.]
 [ 64.   0.   2.]
 [ 64.   3.   5.]
 [ 64.   6.   8.]
 [ 64.   0.   6.]
 [ 64.   1.   7.]
 [ 64.   2.   8.]
 [125.   0.   5.]
 [125.   3.   2.]
 [125.   3.   8.]
 [125.   6.   5.]
 [125.   0.   7.]
 [125.   1.   6.]
 [125.   1.   8.]
 [125.   2.   7.]
 [512.   0.   8.]
 [512.   6.   2.]]


In [98]:
o,v_mat = construct_mats(interaction_list,9)

In [99]:
print(v_mat)

tf.Tensor(
[[1.         1.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         1.         1.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         1.         1.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         1.         1.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.         1.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         1.         1.        ]
 [1.         0.         0.         1.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         1.         0.         0.
  1.         0.         0.        ]
 [0.         1.         0.         0.         1.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         1.         0.
  0.         1.         0.        ]
 [0.         0.         1.   

In [100]:
def log_function_test(samples):
    return tf.reduce_sum(tf.math.log(samples),axis=1)

In [101]:
test_samples = tf.ones((10,9))
log_function_test(test_samples)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [102]:
energy_func = get_Rydberg_Energy_Vectorized(interaction_list,log_function_test)

getting energy function!


In [103]:
test_sample = np.array([[1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99]])

In [104]:
print(test_sample)

[[ 1  2  3  4  5  6  7  8  9]
 [11 22 33 44 55 66 77 88 99]]


In [105]:
test_sample_tf = tf.convert_to_tensor(test_sample,dtype=tf.float32
                                     )
og_logs = log_function_test(test_sample_tf)
print(test_sample_tf)

tf.Tensor(
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [11. 22. 33. 44. 55. 66. 77. 88. 99.]], shape=(2, 9), dtype=float32)


In [106]:
energies = energy_func(Omega,low,V0,o,v_mat,test_sample_tf,og_logs)

shape of term 1:  (2,)
shape of term 2:  (2,)
tile samples:  (2, 9, 9)
The tiled samples are:
tf.Tensor(
[[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.]
  [ 3.  3.  3.  3.  3.  3.  3.  3.  3.]
  [ 4.  4.  4.  4.  4.  4.  4.  4.  4.]
  [ 5.  5.  5.  5.  5.  5.  5.  5.  5.]
  [ 6.  6.  6.  6.  6.  6.  6.  6.  6.]
  [ 7.  7.  7.  7.  7.  7.  7.  7.  7.]
  [ 8.  8.  8.  8.  8.  8.  8.  8.  8.]
  [ 9.  9.  9.  9.  9.  9.  9.  9.  9.]]

 [[11. 11. 11. 11. 11. 11. 11. 11. 11.]
  [22. 22. 22. 22. 22. 22. 22. 22. 22.]
  [33. 33. 33. 33. 33. 33. 33. 33. 33.]
  [44. 44. 44. 44. 44. 44. 44. 44. 44.]
  [55. 55. 55. 55. 55. 55. 55. 55. 55.]
  [66. 66. 66. 66. 66. 66. 66. 66. 66.]
  [77. 77. 77. 77. 77. 77. 77. 77. 77.]
  [88. 88. 88. 88. 88. 88. 88. 88. 88.]
  [99. 99. 99. 99. 99. 99. 99. 99. 99.]]], shape=(2, 9, 9), dtype=float32)
flip tiled samples:  (2, 9, 9)
The tiled and flipped samples are: 
tf.Tensor(
[[[ 2.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 2.  3.  2.  2.  

In [107]:
print(energies)

tf.Tensor([ 2780.5967 30844.932 ], shape=(2,), dtype=float32)
