In [1]:
import sys
sys.path.append('..')

In [2]:
import numpy as np

In [3]:
data_16x16_15MHz_per_us = np.load('../../KZ_Data/KZ_data_16x16_15_MHz_per_us.npz')
data_16x16_21MHz_per_us = np.load('../../KZ_Data/KZ_data_16x16_21_MHz_per_us.npz')
data_16x16_30MHz_per_us = np.load('../../KZ_Data/KZ_data_16x16_30_MHz_per_us.npz')
data_16x16_42MHz_per_us = np.load('../../KZ_Data/KZ_data_16x16_42_MHz_per_us.npz')
data_16x16_60MHz_per_us = np.load('../../KZ_Data/KZ_data_16x16_60_MHz_per_us.npz')
data_16x16_85MHz_per_us = np.load('../../KZ_Data/KZ_data_16x16_85_MHz_per_us.npz')
data_16x16_120MHz_per_us = np.load('../../KZ_Data/KZ_data_16x16_120_MHz_per_us.npz')

### 15 MHz

best because slowest state prep

choose three values of delta: critical, and one on either side

lattice spacing (Rb --> defines V), Omega, delta (basically need the Hamiltonian)

Rb/a = 1.15

delta_C/omega = 1.12 

need to figure out what to do with ryd_resonance (add? subtract?)

In [4]:
file_list_15 = data_16x16_15MHz_per_us.files

In [5]:
for file in file_list_15:
    print(file)
    print(data_16x16_15MHz_per_us[file])

params
[-1.77948113 -1.6615566  -1.54363208 -1.42570755 -1.30778302 -1.18985849
 -1.07193396 -0.95400943 -0.83608491 -0.71816038 -0.60023585 -0.48231132
 -0.36438679 -0.24646226 -0.12853774 -0.01061321  0.10731132  0.22523585
  0.34316038  0.46108491  0.57900943  0.69693396  0.81485849  0.93278302
  1.05070755  1.16863208  1.2865566   1.40448113  1.52240566  1.64033019
  1.75825472  1.87617925  1.99410377  2.1120283   2.22995283  2.34787736
  2.46580189  2.58372642  2.70165094  2.81957547  2.9375      3.05542453
  3.17334906  3.29127358  3.40919811  3.52712264  3.64504717  3.7629717 ]
rydberg_data
[[[[False False False ... False False False]
   [False  True False ... False False False]
   [False False False ... False False False]
   ...
   [ True  True  True ...  True  True  True]
   [ True False False ...  True  True  True]
   [ True  True  True ...  True  True  True]]

  [[False False False ... False False False]
   [False False False ... False False False]
   [False False False ... 

In [6]:
print(np.shape(data_16x16_15MHz_per_us['params']))
print(np.shape(data_16x16_15MHz_per_us['rydberg_data']))

(48,)
(16, 16, 48, 1000)


"params" file contains values for $\frac{\delta}{\Omega}$. Then the last number shows the repititions for that parameter. 16x16 is obviously the lattice size.

In [7]:
deltas = data_16x16_15MHz_per_us['params'] * data_16x16_15MHz_per_us['rabi_freq']
print(deltas + data_16x16_15MHz_per_us['ryd_resonance'])

[-8.  -7.5 -7.  -6.5 -6.  -5.5 -5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5
 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5
  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5
 13.  13.5 14.  14.5 15.  15.5]


In [9]:
print(deltas)

[-7.545 -7.045 -6.545 -6.045 -5.545 -5.045 -4.545 -4.045 -3.545 -3.045
 -2.545 -2.045 -1.545 -1.045 -0.545 -0.045  0.455  0.955  1.455  1.955
  2.455  2.955  3.455  3.955  4.455  4.955  5.455  5.955  6.455  6.955
  7.455  7.955  8.455  8.955  9.455  9.955 10.455 10.955 11.455 11.955
 12.455 12.955 13.455 13.955 14.455 14.955 15.455 15.955]


I think the above values are the physical values of delta that get controlled in the lab. I think the ryd_resonance is some intrinsic resonance that competes with the lab-controlled delta, so the deltas (based on values in params) are the "net delta" which is to say the delta applied in the lab plus the intrinsic resonance. (This is what they do in the Export_Raw_Data notebook)

The x-axis in the plots in the paper correspond to the values in params, so I am going to assume that these yield the values for delta that we should use as our Hamiltonian parameters (for VMC and QMC).

### 21 MHz

In [30]:
file_list_21 = data_16x16_21MHz_per_us.files

In [31]:
for file in file_list_21:
    print(file)
    print(data_16x16_21MHz_per_us[file])

params
[-1.77948113 -1.54363208 -1.30778302 -1.07193396 -0.83608491 -0.60023585
 -0.36438679 -0.12853774  0.10731132  0.34316038  0.57900943  0.81485849
  1.05070755  1.2865566   1.52240566  1.75825472  1.99410377  2.22995283
  2.46580189  2.70165094  2.9375      3.17334906  3.40919811  3.64504717]
rydberg_data
[[[[False False False ... False False False]
   [False False False ... False False False]
   [ True False False ... False False False]
   ...
   [ True  True  True ...  True  True  True]
   [ True  True  True ...  True  True False]
   [ True False  True ...  True False  True]]

  [[False False False ... False False False]
   [ True  True False ... False False False]
   [False False  True ... False False False]
   ...
   [False False  True ... False False False]
   [False False False ... False False  True]
   [ True False  True ... False  True False]]

  [[False False False ... False False  True]
   [False False False ... False False  True]
   [False False False ... False False F

In [32]:
print(np.shape(data_16x16_21MHz_per_us['params']))
print(np.shape(data_16x16_21MHz_per_us['rydberg_data']))

(24,)
(16, 16, 24, 500)


different number of params per frequency... just something to note

### 30 MHz

In [37]:
file_list_30 = data_16x16_30MHz_per_us.files

In [38]:
for file in file_list_30:
    print(file)
    print(data_16x16_30MHz_per_us[file])

params
[-1.77948113 -1.54363208 -1.30778302 -1.07193396 -0.83608491 -0.60023585
 -0.36438679 -0.12853774  0.10731132  0.34316038  0.57900943  0.81485849
  1.05070755  1.2865566   1.52240566  1.75825472  1.99410377  2.22995283
  2.46580189  2.70165094  2.9375      3.17334906  3.40919811  3.64504717]
rydberg_data
[[[[False  True False ... False False False]
   [False False False ... False False False]
   [False False False ... False False False]
   ...
   [ True  True False ...  True  True  True]
   [ True  True  True ...  True False False]
   [ True  True  True ...  True  True  True]]

  [[False False False ... False False False]
   [False False False ... False False False]
   [False False False ... False False False]
   ...
   [False False  True ... False False False]
   [False False False ...  True  True  True]
   [False False False ... False False False]]

  [[False False False ... False False  True]
   [False False False ... False False False]
   [False False False ... False False F

In [39]:
print(np.shape(data_16x16_30MHz_per_us['params']))
print(np.shape(data_16x16_30MHz_per_us['rydberg_data']))

(24,)
(16, 16, 24, 500)


### 42 MHz

In [40]:
file_list_42 = data_16x16_42MHz_per_us.files

In [41]:
for file in file_list_42:
    print(file)
    print(data_16x16_42MHz_per_us[file])

params
[-1.77948113 -1.54363208 -1.30778302 -1.07193396 -0.83608491 -0.60023585
 -0.36438679 -0.12853774  0.10731132  0.34316038  0.57900943  0.81485849
  1.05070755  1.2865566   1.52240566  1.75825472  1.99410377  2.22995283
  2.46580189  2.70165094  2.9375      3.17334906  3.40919811  3.64504717]
rydberg_data
[[[[False False False ... False  True False]
   [False False False ... False False False]
   [False False False ... False False False]
   ...
   [False  True False ...  True  True False]
   [False  True  True ...  True  True  True]
   [ True  True  True ... False  True  True]]

  [[False False False ... False  True False]
   [False False  True ...  True False False]
   [False False False ...  True False False]
   ...
   [ True  True  True ... False False  True]
   [ True False False ... False False False]
   [False False False ...  True  True  True]]

  [[False False False ... False False False]
   [False False False ... False False False]
   [False False False ... False False F

In [42]:
print(np.shape(data_16x16_42MHz_per_us['params']))
print(np.shape(data_16x16_42MHz_per_us['rydberg_data']))

(24,)
(16, 16, 24, 500)


### 60 MHz

In [43]:
file_list_60 = data_16x16_60MHz_per_us.files

In [44]:
for file in file_list_60:
    print(file)
    print(data_16x16_60MHz_per_us[file])

params
[-1.77948113 -1.54363208 -1.30778302 -1.07193396 -0.83608491 -0.60023585
 -0.36438679 -0.12853774  0.10731132  0.34316038  0.57900943  0.81485849
  1.05070755  1.2865566   1.52240566  1.75825472  1.99410377  2.22995283
  2.46580189  2.70165094  2.9375      3.17334906  3.40919811  3.64504717]
rydberg_data
[[[[False False False ... False False False]
   [False False False ... False False False]
   [False False False ... False False False]
   ...
   [ True  True  True ...  True  True False]
   [ True False  True ...  True False  True]
   [ True  True  True ...  True  True  True]]

  [[False False False ... False False False]
   [False False False ... False  True False]
   [False False False ... False False False]
   ...
   [False False False ... False False  True]
   [False  True False ... False False  True]
   [ True  True False ... False False False]]

  [[False False False ... False False False]
   [False False False ... False False False]
   [False False False ... False False  

In [45]:
print(np.shape(data_16x16_60MHz_per_us['params']))
print(np.shape(data_16x16_60MHz_per_us['rydberg_data']))

(24,)
(16, 16, 24, 500)


### 85 MHz

In [46]:
file_list_85 = data_16x16_85MHz_per_us.files

In [47]:
for file in file_list_85:
    print(file)
    print(data_16x16_85MHz_per_us[file])

params
[-1.77948113 -1.54363208 -1.30778302 -1.07193396 -0.83608491 -0.60023585
 -0.36438679 -0.12853774  0.10731132  0.34316038  0.57900943  0.81485849
  1.05070755  1.2865566   1.52240566  1.75825472  1.99410377  2.22995283
  2.46580189  2.70165094  2.9375      3.17334906  3.40919811  3.64504717]
rydberg_data
[[[[False False False ... False  True False]
   [False False False ... False False False]
   [False False  True ... False  True False]
   ...
   [False  True  True ...  True False False]
   [ True  True  True ...  True  True  True]
   [ True  True  True ... False  True  True]]

  [[False False  True ... False False False]
   [False False False ... False False False]
   [False False False ... False False False]
   ...
   [ True False False ... False  True  True]
   [ True False False ... False False  True]
   [False False  True ...  True False False]]

  [[ True  True False ... False False False]
   [False False False ... False False False]
   [ True False False ... False False F

In [48]:
print(np.shape(data_16x16_85MHz_per_us['params']))
print(np.shape(data_16x16_85MHz_per_us['rydberg_data']))

(24,)
(16, 16, 24, 500)


### 120 MHz

In [49]:
file_list_120 = data_16x16_120MHz_per_us.files

In [50]:
for file in file_list_120:
    print(file)
    print(data_16x16_120MHz_per_us[file])

params
[-1.77948113 -1.54363208 -1.30778302 -1.07193396 -0.83608491 -0.60023585
 -0.36438679 -0.12853774  0.10731132  0.34316038  0.57900943  0.81485849
  1.05070755  1.2865566   1.52240566  1.75825472  1.99410377  2.22995283
  2.46580189  2.70165094  2.9375      3.17334906  3.40919811  3.64504717]
rydberg_data
[[[[ True False False ... False False False]
   [False False False ... False False False]
   [False False False ... False False False]
   ...
   [ True  True  True ...  True  True  True]
   [ True False False ... False  True  True]
   [ True  True  True ... False False  True]]

  [[False False False ... False False False]
   [False  True False ... False False False]
   [False False False ... False False False]
   ...
   [False  True  True ... False False False]
   [False False  True ...  True  True False]
   [ True False  True ...  True  True False]]

  [[False  True False ... False False False]
   [False False False ... False False False]
   [False False False ... False False F

In [51]:
print(np.shape(data_16x16_120MHz_per_us['params']))
print(np.shape(data_16x16_120MHz_per_us['rydberg_data']))

(24,)
(16, 16, 24, 500)


## Closer look at "params" files 

In [53]:
print(data_16x16_15MHz_per_us['params'])
print(data_16x16_21MHz_per_us['params'])
print(data_16x16_30MHz_per_us['params'])
print(data_16x16_42MHz_per_us['params'])
print(data_16x16_60MHz_per_us['params'])
print(data_16x16_85MHz_per_us['params'])
print(data_16x16_120MHz_per_us['params'])

[-1.77948113 -1.6615566  -1.54363208 -1.42570755 -1.30778302 -1.18985849
 -1.07193396 -0.95400943 -0.83608491 -0.71816038 -0.60023585 -0.48231132
 -0.36438679 -0.24646226 -0.12853774 -0.01061321  0.10731132  0.22523585
  0.34316038  0.46108491  0.57900943  0.69693396  0.81485849  0.93278302
  1.05070755  1.16863208  1.2865566   1.40448113  1.52240566  1.64033019
  1.75825472  1.87617925  1.99410377  2.1120283   2.22995283  2.34787736
  2.46580189  2.58372642  2.70165094  2.81957547  2.9375      3.05542453
  3.17334906  3.29127358  3.40919811  3.52712264  3.64504717  3.7629717 ]
[-1.77948113 -1.54363208 -1.30778302 -1.07193396 -0.83608491 -0.60023585
 -0.36438679 -0.12853774  0.10731132  0.34316038  0.57900943  0.81485849
  1.05070755  1.2865566   1.52240566  1.75825472  1.99410377  2.22995283
  2.46580189  2.70165094  2.9375      3.17334906  3.40919811  3.64504717]
[-1.77948113 -1.54363208 -1.30778302 -1.07193396 -0.83608491 -0.60023585
 -0.36438679 -0.12853774  0.10731132  0.34316038 

The values of params is the same for each sweep rate except for first one (15 MHz), which has an intermediate parameter value between the 24 values found in each of the other files. This is why there are 48 parameter values there and only 24 in all the others. Its also worth noting that at this sweep rate, double the repititions were performed. Not sure why.

## Need to convert boolean into binary

In [55]:
rydberg_data_15 = data_16x16_15MHz_per_us['rydberg_data']

In [56]:
print(np.shape(rydberg_data_15))

(16, 16, 48, 1000)


In [58]:
print(rydberg_data_15[:,:,0,0].astype(int))

[[0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [59]:
from dset_helpers import bool_to_bin

In [62]:
bin_data_15 = bool_to_bin(rydberg_data_15)

print(bin_data_15)
print(np.shape(bin_data_15))

[[[[0 0 0 ... 0 0 0]
   [0 1 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [1 1 1 ... 1 1 1]
   [1 0 0 ... 1 1 1]
   [1 1 1 ... 1 1 1]]

  [[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 1]
   ...
   [0 1 0 ... 0 0 0]
   [1 1 0 ... 1 0 0]
   [1 1 0 ... 0 0 0]]

  [[1 1 0 ... 0 0 0]
   [1 0 0 ... 0 0 0]
   [0 0 0 ... 1 0 0]
   ...
   [1 0 1 ... 1 1 1]
   [0 0 1 ... 1 1 1]
   [0 0 1 ... 1 1 1]]

  ...

  [[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 1 0 ... 1 1 1]
   [0 1 0 ... 0 1 1]
   [1 1 1 ... 1 1 0]]

  [[1 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 1 0 0]
   [1 0 0 ... 1 0 0]
   [0 0 0 ... 0 0 1]]

  [[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 1]
   ...
   [1 0 1 ... 0 1 1]
   [0 1 1 ... 0 1 1]
   [1 1 1 ... 1 1 1]]]


 [[[0 0 0 ... 0 1 0]
   [0 0 0 ... 0 0 0]
   [0 0 1 ... 0 0 0]
   ...
   [0 1 0 ... 0 0 0]
   [1 0 1 ... 1 0 0]
   [0 1 0 ... 0 0 0]]

  [[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [

This should also work for obtaining the rearranging mask

In [65]:
bin_rearrange_mask = bool_to_bin(data_16x16_15MHz_per_us['rearrange_mask'])
print(bin_rearrange_mask)
print(np.shape(bin_rearrange_mask))

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(48, 1000)


I dont really know what the rearrange mask is all about... but our bool to binary conversion works for it too...