We will examine the Rydberg Hamiltonian with
   - $\frac{R_b}{a} = 1.15$
   - $\Omega = 4.24$
   - $\delta = {-1.545, 4.455, 4.955, 13.455}$ 

The four values of $\delta$ correspond to different points along the phase transition. The low and high values correspond to the ordered and disordered phases (respectively), and the two middle values are those closest to the critical value of $\delta$

In [1]:
%load_ext autoreload
%autoreload 2

In [15]:
import sys
sys.path.append('..')
import numpy as np
from dset_helpers import data_given_param,create_KZ_tf_dataset

In [16]:
sweep_rate = 15
low = -1.545
midlow = 4.455
midhigh = 4.955
high = 13.455

In [17]:
data_low = data_given_param(sweep_rate,low)
data_midlow = data_given_param(sweep_rate,midlow)
data_midhigh = data_given_param(sweep_rate,midhigh)
data_high = data_given_param(sweep_rate,high)

In [18]:
print(np.shape(data_low))

(16, 16, 1, 1000)


In [19]:
low_tf = create_KZ_tf_dataset(data_low)

In [20]:
print(low_tf)

tf.Tensor(
[[0 1 1 ... 1 0 0]
 [0 0 0 ... 0 0 1]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]], shape=(256, 1000), dtype=int64)
