In [1]:
import numpy as np
import tensorflow as tf

In [2]:
import sys
sys.path.append('..')
from stag_mag import coord_to_site,generate_sublattices_square,calculate_stag_mag

In [3]:
Lx = 4
Ly = 4
array = np.zeros((Lx,Ly))

for i in range(Lx):
    for j in range(Ly):
        site = coord_to_site(Lx,i,j)
        array[i,j] = site
        print("y = ", i,"; x = ",j)
        print("Site number is: ",site)


print("Array view:\n",array)

y =  0 ; x =  0
Site number is:  0
y =  0 ; x =  1
Site number is:  1
y =  0 ; x =  2
Site number is:  2
y =  0 ; x =  3
Site number is:  3
y =  1 ; x =  0
Site number is:  4
y =  1 ; x =  1
Site number is:  5
y =  1 ; x =  2
Site number is:  6
y =  1 ; x =  3
Site number is:  7
y =  2 ; x =  0
Site number is:  8
y =  2 ; x =  1
Site number is:  9
y =  2 ; x =  2
Site number is:  10
y =  2 ; x =  3
Site number is:  11
y =  3 ; x =  0
Site number is:  12
y =  3 ; x =  1
Site number is:  13
y =  3 ; x =  2
Site number is:  14
y =  3 ; x =  3
Site number is:  15
Array view:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [4]:
a_coords,b_coords,a_sites,b_sites = generate_sublattices_square(Lx,Ly)

In [5]:
print("a coordinates:\n",a_coords)
print("a sites:\n",a_sites)
print("b coordinates:\n",b_coords)
print("b sites:\n",b_sites)

a coordinates:
 [(0, 0), (0, 2), (1, 1), (1, 3), (2, 0), (2, 2), (3, 1), (3, 3)]
a sites:
 [0, 2, 5, 7, 8, 10, 13, 15]
b coordinates:
 [(0, 1), (0, 3), (1, 0), (1, 2), (2, 1), (2, 3), (3, 0), (3, 2)]
b sites:
 [1, 3, 4, 6, 9, 11, 12, 14]


In [6]:
allup = np.ones((5,Lx*Ly))
alldown = np.zeros((1,Lx*Ly))

In [7]:
print(allup)
print(alldown)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
print(calculate_stag_mag(Lx,Ly,allup))

(array([0., 0., 0., 0., 0.]), 0.0, 0.0, 0.0)


In [9]:
random = np.random.randint(0,2,(10,Lx*Ly))

In [10]:
print(random)

[[1 0 1 0 0 0 1 0 1 0 1 0 1 0 0 0]
 [1 1 1 1 0 0 1 1 0 1 1 1 0 1 0 1]
 [0 1 1 1 1 0 1 1 1 0 0 0 0 0 1 0]
 [0 1 1 1 1 1 1 1 0 0 1 1 0 1 1 1]
 [1 1 1 0 1 0 0 0 1 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 1 0 1 0 1 1 1 1]
 [0 1 0 1 0 1 0 0 0 0 1 0 1 1 0 1]
 [0 0 1 1 1 0 0 0 1 0 1 0 1 0 1 1]]


In [11]:
print(calculate_stag_mag(Lx,Ly,random))

(array([-0.125 , -0.0625,  0.125 ,  0.    ,  0.0625, -0.0625,  0.0625,
       -0.0625, -0.0625,  0.    ]), -0.0125, 0.0625, 0.0053125)


seems correct

In [13]:
sample = np.array([[1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1]])
print(calculate_stag_mag(Lx,Ly,sample))

(array([-0.5]), -0.5, 0.5, 0.0)


In [14]:
sample_array = np.reshape(sample,(Lx,Ly))
print(sample_array)

[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


The above example shows that the stag mag for checkerboard phase should be 0.5

In [17]:
sample_flipped = -1*sample + 1
sample_flipped_array = np.reshape(sample_flipped,(Lx,Ly))

In [18]:
print(sample_flipped_array)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [19]:
print(calculate_stag_mag(Lx,Ly,sample_flipped))

(array([0.5]), 0.5, 0.5, 0.0)


So the absolute value of the staggered magnetization is 0.5 for the checkerboard phase